### ISSUE TITLE
failed to build project via make with z3

### ISSUE THREAD

**Issue by chemicsbear** [Rammbock9000/sat_scm#1]
Hi, I am not very good at programming, when I run make with z3, it ran into an error saying no such file or directory z3++.h,in the mcm_z3.h file, and after trying to rename the include from z3++.h to z3.h, many error occur.

**Comment by Rammbock9000** [comment]
Hi,

thanks for your iterest in our project! I have two questions:

1) How did you install Z3? Do you have a directory (e.g., "/opt/z3/") that
contains subdirectories "include/" and "lib/"? If yes, does "lib/" contain
"libz3.so" and does "include/" contain "z3++.h"?
Normally, re-naming files in mcm_z3.h should not be necessary.
Alternatively, you could try using the CaDiCaL backend (
https://github.com/arminbiere/cadical). For our use cases CaDiCaL was
usually faster than Z3 by a factor of 10x (even when using multithreading
with Z3).

2) What exactly was your cmake call? In my case, I have Z3 installed in
"/opt/z3/z3-4.8.17/" so I use "cmake
-DCMAKE_PREFIX_PATH="/opt/z3/z3-4.8.17/" ." and afterwards "make" to
install the program.

Best regards, Nicolai

Am Do., 20. Juli 2023 um 08:25 Uhr schrieb chemicsbear <
***@***.***>:

**Comment by Rammbock9000** [comment]
Hi, what exactly was your cmake call? In my case, I have Z3 installed in '/opt/z3/z3-4.8.17/' so I use 'cmake -DCMAKE_PREFIX_PATH="/opt/z3/z3-4.8.17/" .' and afterwards 'make' to install the program.

**Comment by chemicsbear** [comment]
Thank you very much for your reply, after reading your comment, I have looked into the folder of z3, and found that the z3++.h is not in the same folder with z3.h, the problem is fixed after copying the z3++.h to the same folder as z3.h
